// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('angularYeomanApp').controller('MainCtrl', function($scope, hudlayout_res) {
    var editor, key, obj, r, xposToNum, yposToNum, _i, _len, _ref;

    $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
    $scope.hudlayout_res = hudlayout_res;
    xposToNum = function(pos) {
      if (pos == null) {
        pos = '0';
      }
      if (pos[0] === 'r') {
        return 640 - (+pos.substring(1));
      }
      if (pos[0] === 'c') {
        return 320 + pos.substring(1);
      }
      if (pos[0] === 'z') {
        return 10;
      }
      return +pos;
    };
    yposToNum = function(pos) {
      if (pos == null) {
        pos = '0';
      }
      if (pos[0] === 'r') {
        return 480 - (+pos.substring(1));
      }
      if (pos[0] === 'c') {
        return 240 + pos.substring(1);
      }
      if (pos[0] === 'z') {
        return 10;
      }
      return +pos;
    };
    editor = new fabric.Canvas('editor');
    window.editor = editor;
    _ref = Object.keys(hudlayout_res);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      obj = hudlayout_res[key];
      r = new fabric.Rect({
        left: xposToNum(obj.xpos),
        top: yposToNum(obj.ypos),
        width: xposToNum(obj.wide),
        height: yposToNum(obj.tall),
        opacity: 0.2,
        color: 'red'
      });
      console.log(r);
      editor.add(r);
    }
  });

}).call(this);
